### ISSUE TITLE
DescLenMax is too small

### ISSUE THREAD

**Issue by johnperry-math** [lboasso/oberonc#6] opened 2018-05-18 00:12 UTC
Compilation failed because `DescLenMax` in `ClassFormat.Mod` is only 100. That's not long enough for most function names, where there can be many variables with long type names. Increasing it to 1000 got a program to move past one compilation error for me, but I'm not sure 1000 is enough, either.

I can submit a pull request if you like, but this seems easy enough to fix for now.

**Comment by johnperry-math** [comment] 2018-05-18 02:35
Hi

I was trying it out for fun. I was [implementing this "completely unscientific benchmark](https://github.com/frol/completely-unscientific-benchmarks) in Oberon-2 and yours is the first Oberon-2 compiler I've ever been able to make work in decades (1999 in fact, I think). The procedure that gave me trouble is

    PROCEDURE Merge(lower, greater: NodePtr): NodePtr;

whose signature is, if I recall correctly, to the effect of

    ( CompleteUnscientificBenchmark_Node; CompleteUnscientificBenchmark_Node;) CompleteUnscientificBenchmark_Node

(I had it printing signatures out at one point, which is why I remember that.)

I can upload a copy of the files I wrote if you like. After a bit of work, I did get it to compile.

**Comment by lboasso** [comment] 2018-05-18 03:31
I am happy you managed to compile and run your benchmark :smile:. 

This compiler is for the Oberon-07 language, Niklaus Wirth revived the original Oberon in 2007, there are a few additions and restrictions in the new version. The document ["Difference between Oberon-07 and Oberon"](http://www-oldurls.inf.ethz.ch/personal/wirth/Oberon/Oberon07.pdf) gives a nice overview.

Please upload a copy of the files, I would like to compile you benchmark locally.

**Comment by johnperry-math** [comment] 2018-05-18 03:53
> This compiler is for the Oberon-07 language, Niklaus Wirth revived the original Oberon in 2007, there are a few additions and restrictions in the new version.

I think it was Oberon-2 that I toyed with back then. To be honest, I was more of a Modula-2 programmer in the 90s (*when* I programmed, which has generally been more for pleasure than for employment).

> Please upload a copy of the files, I would like to compile you benchmark locally.

I was going to attach it to this, but apparently it's not allowed. I'll try to figure out how to upload a file here, but if you have any suggestions I'm open to them. Worst comes to worst I'll just create a new repository in my account.

**Comment by johnperry-math** [comment] 2018-05-18 04:15
After reading just a little on GitHub, I decided to upload it here:

    https://github.com/johnperry-math/completely-unscientific-benchmarks/tree/master/oberon07

You don't need the whole distribution; just that directory should do.

If you have any advice on how to improve it, I'd be much obliged. On my machine it takes about twice as long as the Java version, which itself takes about twice as long as the C++, Ada, and Modula-2 versions.

**Comment by lboasso** [comment] 2018-05-18 04:31
Thanks for uploading! 
Since it compiles to regular Java bytecode, it should be possible to make it as fast as the Java version.
Let me take a look

**Comment by johnperry-math** [comment] 2018-05-18 22:09
With javap I took a look at the bytecode produced for initialization of a new class element by both javac and oberonc. In the Java code I guess that's just the constructor `Node()`; in the Oberon code it's `InitNode()`. I noticed the following two differences:

- Initialization
  - javac initializes an object immediately with `java/lang/Object."<init>":()V`.
  - oberonc invokes `new`, then invokes special `_Node.init`. I think one of those two invokes the Node constructor, which invokes Java's code (including `java/lang/Object."<init>":()V`) but I'm not familiar enough with them (or your code) to say
- Storage
  - javac works merely with local elements: `aload`, `iload`
  - oberonc seems to work with arrays; there are a lot of `aastore`'s and `aaload`'s going around; does it consider `NodePtr` as an element of an array of length 1?

**Comment by johnperry-math** [comment] 2018-05-18 22:56
> Initialization

This is actually taken care of in the Java code elsewhere, in `Tree.class`, so that's not a real difference, after all.

**Comment by lboasso** [comment] 2018-05-19 04:12
I like that you resorted to javap and started analyzing the bytecode! Good job! :smile: 
There are a couple of places were implementing Oberon-07 semantics resulted in more bytecode emitted compared to Java code. Variable parameters is one example, as the Java Virtual Machine does not support natively this parameter passing mode, the semantic is emulated by using arrays of length one as parameters. For more information see ["Parameter Passing for the Java Virtual Machine"](http://oberon2005.oberoncore.ru/paper/p_jvm2.pdf). In general, thanks to the good JVM's JIT compiler, this does not pose substantial performance penalties.

I did a couple of experiments to see why your benchmark was slower, and after profiling the code I  found the root cause.  The main loop is running in the module body:

```
MODULE CompleteUnscientificBenchmark;
IMPORT Rand := RandomInt, Out;

TYPE
(*...*)

VAR
   t: Tree;
   i, cur, res, mode: INTEGER;
(*...*)

BEGIN
   Rand.Init();
   cur := 5; res := 0;
   FOR i := 1 TO 999999 DO
      mode := i MOD 3;
      cur := (cur * 57 + 43) MOD 10007;
      IF mode = 0 THEN Insert(t, cur);
      ELSIF mode = 1 THEN Erase(t, cur);
      ELSE res := res + HasValue(t, cur);
      END; (* IF *)
   END; (* FOR *)
   Out.Int(res, 0); Out.Ln;
END CompleteUnscientificBenchmark.
```

So it makes extensive use of the global variables  `t`, `i`, `cur`, `res`, and `mode`. Usually this is not a problem, but in a loop with so many iterations, you start seeing the overhead of global variables accessing compared to local ones. In the Java version of the the same benchmark, those variables are local to the `main` method. So if you change your code like below, you will see that your benchmark will run at a speed comparable to the Java version.

```
MODULE CompleteUnscientificBenchmark;
IMPORT Rand := RandomInt, Out;

TYPE
(*...*)

PROCEDURE Run();
VAR
   t: Tree;
   i, cur, res, mode: INTEGER;
BEGIN
 Rand.Init();
 cur := 5; res := 0;
 FOR i := 1 TO 999999 DO
    mode := i MOD 3;
    cur := (cur * 57 + 43) MOD 10007;
    IF mode = 0 THEN Insert(t, cur);
    ELSIF mode = 1 THEN Erase(t, cur);
    ELSE res := res + HasValue(t, cur);
    END; (* IF *)
 END; (* FOR *)
 Out.Int(res, 0); Out.Ln;
END Run;

BEGIN
  Run()
END CompleteUnscientificBenchmark.
```

**Comment by johnperry-math** [comment] 2018-05-19 05:06
> I did a couple of experiments to see why your benchmark was slower, and after profiling the code I found the root cause.

Thank you! Can I ask how you profiled it? I'm not familiar with profiling in Java.

> Usually this is not a problem, but in a loop with so many iterations, you start seeing the overhead of global variables accessing compared to local ones. In the Java version of the the same benchmark, those variables are local to the `main` method. So if you change your code like below, you will see that your benchmark will run at a speed comparable to the Java version.

I was really impressed when I saw that result with my own eyes!

> Variable parameters is one example, as the Java Virtual Machine does not support natively this parameter passing mode, the semantic is emulated by using arrays of length one as parameters. For more information see ["Parameter Passing for the Java Virtual Machine"](http://oberon2005.oberoncore.ru/paper/p_jvm2.pdf).

Thank you for the paper; that's really informative. I had, uh, experimented with removing initialization code the compiler wanted to insert, and I kept encountering class verification errors. Now I understand why. I also see that I was looking at it in completely the wrong way.

**Comment by lboasso** [comment] 2018-05-20 02:37
> Thank you! Can I ask how you profiled it? I'm not familiar with profiling in Java.

For profiling Java I like [VisualVM](https://visualvm.github.io/), but in oder to find the root cause of the performance issue, small experiments were more effective.

> I was really impressed when I saw that result with my own eyes!

I was surprised myself, it is always like that with performance tuning, guessing performance bottlenecks does not lead you anywhere, measuring is key. Initially I have even rewritten the whole benchmark from Java to Oberon, avoiding variable parameters (first guess of root cause), but it turned out that their overhead is negligible.

I have updated the DescLenMax constant, I'll close this issue, but feel free to reach me out by email.

**Closed by lboasso** 2018-05-20 02:37 UTC
